db:
  data:
    postgres-password: "${postgresql.password}"
    replication-password: "${postgresql.password}"
    password: "${postgresql.password}"
    redis-password: "${redis.password}"

origin-cert:
  data:
    "server.key": "${certificate_key}"
    "server.crt": "${certificate_cert}"

global:
  data:
    POSTGRES_PASSWORD: "${postgresql.password}"
    REDIS_PASSWORD: "${redis.password}"
